name: torch2_cuda11.8
channels:
  - pytorch
  - pyg
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.5=py310h9128911_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotlipy=0.7.0=py310h2bbff1b_1002
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2023.7.22=h56e8100_0
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2bbff1b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - contourpy=1.0.5=py310h59b6b97_0
  - cryptography=41.0.2=py310hac1b9e3_0
  - cuda-cccl=12.2.140=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-profiler-api=12.2.140=0
  - cuda-runtime=11.8.0=0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.6.7=py310hd77b12b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - filelock=3.9.0=py310haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - giflib=5.2.1=h8cc25b3_3
  - glib=2.69.1=h5dc1a3c_2
  - icc_rt=2022.1.0=h6049295_2
  - icu=58.2=ha925a31_3
  - idna=3.4=py310haa95532_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46319
  - ipykernel=6.25.1=pyh6817e22_0
  - ipython=8.14.0=pyh08f2357_0
  - isodate=0.6.1=pyhd8ed1ab_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jinja2=3.1.2=py310haa95532_0
  - joblib=1.2.0=py310haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py310h5588dad_0
  - kiwisolver=1.4.4=py310hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcurand=10.3.3.141=0
  - libcurand-dev=10.3.3.141=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h2bbff1b_0
  - libffi=3.4.4=hd77b12b_0
  - libiconv=1.16=h2bbff1b_2
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.15=h906ac69_1
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.5.0=h6c2663c_2
  - libuv=1.44.2=h2bbff1b_0
  - libwebp=1.2.4=hbc33d0d_1
  - libwebp-base=1.2.4=h2bbff1b_1
  - libxml2=2.10.4=h0ad7f3c_1
  - libxslt=1.1.37=h2bbff1b_1
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.1=py310h2bbff1b_0
  - matplotlib=3.7.1=py310haa95532_1
  - matplotlib-base=3.7.1=py310h4ed8f06_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46357
  - mkl-service=2.4.0=py310h2bbff1b_1
  - mkl_fft=1.3.6=py310h4ed8f06_1
  - mkl_random=1.2.2=py310h4ed8f06_1
  - mpmath=1.3.0=py310haa95532_0
  - munkres=1.1.4=py_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=py310haa95532_0
  - numexpr=2.8.4=py310h2cd9be0_1
  - numpy=1.25.2=py310h055cbcc_0
  - numpy-base=1.25.2=py310h65a83cf_0
  - openssl=3.0.10=h2bbff1b_2
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.0.3=py310h4ed8f06_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=hd77b12b_0
  - pickleshare=0.7.5=py_1003
  - pillow=9.4.0=py310hd77b12b_0
  - pip=23.2.1=py310haa95532_0
  - platformdirs=3.10.0=py310haa95532_0
  - ply=3.11=py310haa95532_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.0=py310h2bbff1b_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.3.1=py310_torch_2.0.0_cu118
  - pygments=2.16.1=pyhd8ed1ab_0
  - pyopenssl=23.2.0=py310haa95532_0
  - pyparsing=3.0.9=py310haa95532_0
  - pyqt=5.15.7=py310hd77b12b_0
  - pyqt5-sip=12.11.0=py310hd77b12b_0
  - pysocks=1.7.1=py310haa95532_0
  - python=3.10.12=he1021f5_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.8_cudnn8_0
  - pytorch-cuda=11.8=h24eeafa_5
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py310haa95532_0
  - pywin32=305=py310h2bbff1b_0
  - pyzmq=23.2.1=py310h73ada01_0
  - qt-main=5.15.2=h879a1e9_9
  - qt-webengine=5.15.9=h5bd16bc_7
  - qtwebkit=5.212=h2bbfb41_5
  - rdflib=7.0.0=pyhd8ed1ab_0
  - requests=2.31.0=py310haa95532_0
  - scikit-learn=1.3.0=py310h4ed8f06_0
  - scipy=1.11.1=py310h309d312_0
  - seaborn=0.12.2=py310haa95532_0
  - setuptools=68.0.0=py310haa95532_0
  - sip=6.6.2=py310hd77b12b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.11.1=py310haa95532_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h2bbff1b_0
  - toml=0.10.2=pyhd3eb1b0_0
  - tornado=6.2=py310he2412df_0
  - tqdm=4.65.0=py310h9909e9c_0
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing_extensions=4.7.1=py310haa95532_0
  - tzdata=2023c=h04d1e81_0
  - urllib3=1.26.16=py310haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.38.4=py310haa95532_0
  - win_inet_pton=1.1.0=py310haa95532_0
  - xz=5.4.2=h8cc25b3_0
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.16.2=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - async-timeout==4.0.3
      - attrs==23.1.0
      - cachetools==5.3.1
      - clarabel==0.6.0
      - click==8.1.7
      - cvxpy==1.4.1
      - docker-pycreds==0.4.0
      - ecos==2.0.12
      - frozenlist==1.4.0
      - fsspec==2023.9.2
      - gitdb==4.0.10
      - gitpython==3.1.37
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - grpcio==1.59.0
      - lightning-utilities==0.9.0
      - markdown==3.5
      - multidict==6.0.4
      - oauthlib==3.2.2
      - osqp==0.6.3
      - pathtools==0.1.2
      - protobuf==4.24.4
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pybind11==2.11.1
      - pygraft==0.0.3
      - pytorch-lightning==2.1.0
      - qdldl==0.1.7.post0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scs==3.2.3
      - sentry-sdk==1.32.0
      - setproctitle==1.3.3
      - smmap==5.0.1
      - tensorboard==2.14.1
      - tensorboard-data-server==0.7.1
      - torchaudio==2.0.2
      - torchmetrics==1.2.0
      - torchvision==0.15.2
      - wandb==0.15.12
      - werkzeug==3.0.0
      - yarl==1.9.2
prefix: C:\tools\Anaconda3\envs\torch2_cuda11.8
